# Generated by Django 3.2.2 on 2021-05-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=500)),
                ('discreption', models.TextField(blank=True, null=True)),
                ('deatils', models.TextField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, default='Will update soon', null=True)),
                ('application_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('selected_students', models.TextField(blank=True, default='To be updated', null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
