# Generated by Django 3.2.4 on 2021-06-14 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20210509_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='deatils',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
